# Site settings
name: bilc
email: bilc-dev@163.com
author: bilc
url: bilc.github.io
resume_site: https://github.com/bilc/
github: https://github.com/bilc/
baseurl: ""
description: Actually, less is more!
meta_description: ""
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bilc

# Build settings
markdown: kramdown

baidu_analysis: 7710fb780753dcd01e0b8c75e36e2e07

